#!/bin/sh -e

### Permissions
# 700 ~/.ssh
# 400 ~/.ssh/id_rsa
# 400 ~/.ssh/id_rsa.pub
# 600 ~/.ssh/config

sshDir=~/.ssh
sshPrivateKey=$sshDir/id_rsa
sshPublicKey=$sshDir/id_rsa.pub
sshConfig=$sshDir/config
gitConfig=~/.gitconfig

secretDir=/var/run/secrets
secretKey=${secretDir}/.ssh/id_rsa
secretKeyPub=${secretDir}/.ssh/id_rsa.pub
secretSshConfig=${secretDir}/.ssh/config
secretGitConfig=${secretDir}/.git/.gitconfig

if [ -d ${sshDir} ]; then
    chmod 700 ${sshDir}
    if [ -f ${sshPrivateKey} ]; then
        chmod 400 ${sshPrivateKey}
    elif [ -f ${secretKey} ]; then
        cp ${secretKey} ${sshPrivateKey} && chmod 400 ${sshPrivateKey}
    elif [ -n "${SSH_PRIVATE_KEY}" ] && [ "${SSH_PRIVATE_KEY}" != "" ]; then
        echo "${SSH_PRIVATE_KEY}" > ${sshPrivateKey} && chmod 400 ${sshPrivateKey}
    fi
    if [ -f ${sshPublicKey} ]; then
        chmod 400 ${sshPublicKey}
    elif [ -f ${secretKeyPub} ]; then
        cp ${secretKeyPub} ${sshPublicKey} && chmod 400 ${sshPublicKey}
    elif [ -n "${SSH_PUBLIC_KEY}" ] && [ "${SSH_PUBLIC_KEY}" != "" ]; then
        echo "${SSH_PUBLIC_KEY}" > ${sshPublicKey} && chmod 400 ${sshPublicKey}
    fi
    if [ -f ${sshConfig} ]; then
        chmod 600 ${sshConfig}
    elif [ -f ${secretSshConfig} ]; then
        cp ${secretSshConfig} ${sshConfig} && chmod 600 ${sshConfig}
    elif [ -n "${SSH_CONFIG}" ] && [ "${SSH_CONFIG}" != "" ]; then
        echo "${SSH_CONFIG}" > ${sshConfig} && chmod 600 ${sshConfig}
    fi
else
    mkdir ${sshDir} && chmod 700 ${sshDir}
    if [ -f ${sshPrivateKey} ]; then
        chmod 400 ${sshPrivateKey}
    elif [ -f ${secretKey} ]; then
        cp ${secretKey} ${sshPrivateKey} && chmod 400 ${sshPrivateKey}
    elif [ -n "${SSH_PRIVATE_KEY}" ] && [ "${SSH_PRIVATE_KEY}" != "" ]; then
        echo "${SSH_PRIVATE_KEY}" > ${sshPrivateKey} && chmod 400 ${sshPrivateKey}
    fi
    if [ -f ${sshPublicKey} ]; then
        chmod 400 ${sshPublicKey}
    elif [ -f ${secretKeyPub} ]; then
        cp ${secretKeyPub} ${sshPublicKey} && chmod 400 ${sshPublicKey}
    elif [ -n "${SSH_PUBLIC_KEY}" ] && [ "${SSH_PUBLIC_KEY}" != "" ]; then
        echo "${SSH_PUBLIC_KEY}" > ${sshPublicKey} && chmod 400 ${sshPublicKey}
    fi
    if [ -f ${sshConfig} ]; then
        chmod 600 ${sshConfig}
    elif [ -f ${secretSshConfig} ]; then
        cp ${secretSshConfig} ${sshConfig} && chmod 600 ${sshConfig}
    elif [ -n "${SSH_CONFIG}" ] && [ "${SSH_CONFIG}" != "" ]; then
        echo "${SSH_CONFIG}" > ${sshConfig} && chmod 600 ${sshConfig}
    fi
fi
if [ -f ${gitConfig} ]; then
    chmod 600 ${gitConfig}
elif [ -f ${secretGitConfig} ]; then
    cp ${secretGitConfig} ${gitConfig} && chmod 600 ${gitConfig}
elif [ -n "${GIT_CONFIG}" ] && [ "${GIT_CONFIG}" != "" ]; then
    echo "${GIT_CONFIG}" > ${gitConfig} && chmod 600 ${gitConfig}
fi
if [ -f ${sshPrivateKey} ]; then
    eval $(ssh-agent -s)  &&  ssh-add ${sshPrivateKey}
fi

sh -c "$@"